// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} name
 * @param {string} addr
 * @returns {$CancellablePromise<void>}
 */
export function AddDevice(name, addr) {
    return $Call.ByID(3497441792, name, addr);
}

/**
 * @returns {$CancellablePromise<$models.DeviceObj[]>}
 */
export function GetDevices() {
    return $Call.ByID(3193616320).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RemoveDevice(name) {
    return $Call.ByID(3014570653, name);
}

/**
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetMode(mode) {
    return $Call.ByID(1897138582, mode);
}

/**
 * @param {string} brightness
 * @returns {$CancellablePromise<void>}
 */
export function StaticRgbSetBrightness(brightness) {
    return $Call.ByID(2181176415, brightness);
}

/**
 * @param {string} color
 * @returns {$CancellablePromise<void>}
 */
export function StaticRgbSetColor(color) {
    return $Call.ByID(534234799, color);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function SwitchEnableState(name) {
    return $Call.ByID(47551641, name);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function SwitchPowerState(name) {
    return $Call.ByID(1810469873, name);
}

// Private type creation functions
const $$createType0 = $models.DeviceObj.createFrom;
const $$createType1 = $Create.Array($$createType0);
