// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DeviceObj {
    /**
     * Creates a new DeviceObj instance.
     * @param {Partial<DeviceObj>} [$$source = {}] - The source object to create the DeviceObj.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Addr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Addr"] = "";
        }
        if (!("Enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceObj instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceObj}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceObj(/** @type {Partial<DeviceObj>} */($$parsedSource));
    }
}
